Vy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vy.DAL;
using Vy.Models;

namespace Vy.Controllers
{
    [HandleError]

    public class HomeController : Controller
    {
        // Return Homepage
        public ActionResult Index()
        {
            Session["Ticket"] = null;
            return View();
        }

        //Return All tickets page
        public ActionResult AllTickets()
        {
            var TicketDAL = new TicketDAL();
            List<Ticket> AllTickets = TicketDAL.getAllTickets();
            return View(AllTickets);
        }
    }
}

Vy/Controllers/ReceiptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vy.Models;
using Vy.DAL;


namespace Vy.Controllers
{
    public class ReceiptController : Controller
    {
        // Save the ticket to database
        [HttpPost]
        public ActionResult getReceipt(Ticket t)
        {

            var TicketDAL = new TicketDAL();

            int newTikcetID = TicketDAL.SaveTicket(t);
            if (newTikcetID != 0)
            {
                return Json(new { id = newTikcetID, newurl = Url.Action("getReceipt") });


            }
            return View();

        }
        // Return one ticket by ID
        [HttpGet]
        public ActionResult getReceipt(int id)
        {
            var TicketDAL = new TicketDAL();
            var t = TicketDAL.getTicketByID(id);
            return View(t);
        }

    }
}

Vy/Views/Home/AllTickets.cshtml
@model IEnumerable<Vy.Models.Ticket>


<h2>All Tickets</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TicketPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketDuration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartStation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndStation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketPurchaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketPurchaseTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderedBy)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TicketPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TicketDuration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartStation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndStation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TicketPurchaseDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TicketPurchaseTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderedBy)
        </td>
        <td>
            @Html.ActionLink("Details","getReceipt", "Receipt", new { id=item.TicketID },null)
        </td>
    </tr>
}

</table>

Vy/Views/Home/Book.cshtml
@model Vy.Models.Passenger

<body>
    <div>
        <form action="/Home/Book" method="post">
            <table class=" table">
                <tr>
                    <td>¨Source</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Destination</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Date Of Journey</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Time Of Journey</td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td></td>
                </tr>



            </table>
        </form>
    </div>
</body>

Vy/Views/Home/Index.cshtml
@model Vy.Models.Ticket



@using (Html.BeginForm(null, null, new { @id = string.Empty }, FormMethod.Post,
    new { @id = "find-ticket-form" }))
{

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="container">
        <div class="row mb-5">
            <div class="col-lg-10 mx-auto">
                <div class="card  border-0 shadow mt-5 mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Welcome to Vy. Where would you like to travel?</h5>
                    </div>
                </div>
                <div class="bg-white p-5 rounded shadow">

                    <div class="row justify-content-around">
                        <div class="col-md-5">

                            @*Departure textbox*@
                            <div class="form-group">
                                <label class="col-form-label info">Departure</label>

                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <button id="button-addon8" class="btn btn-primary" style="color:black;background-color:transparent;border:0.5px solid" disabled><i class="fa fa-search"></i></button>
                                    </div>
                                    @Html.EditorFor(model => model.StartStation, new { htmlAttributes = new { @class = "form-control", id = "station1", type = "search", autocomplete = "off", placeholder = "Where do you travel from?" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.StartStation, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="col-md-5">
                            @*Destination textbox*@
                            <div class="form-group">
                                <label class="col-form-label">Destination</label>

                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <button id="button-addon8" class="btn btn-primary" style="color:black;background-color:transparent;border:0.5px solid" disabled><i class="fa fa-search"></i></button>
                                    </div>
                                    @Html.EditorFor(model => model.EndStation, new { htmlAttributes = new { @class = "form-control", id = "station2", type = "search", autocomplete = "off", placeholder = "Where do you want to go?" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.EndStation, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="row justify-content-around">
                        <div class="col-md-5">
                            @*Date picker*@

                            <div class="form-group">
                                <label class="col-form-label">Date</label>

                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <button id="button-addon7" class="btn btn-primary" style="color:black;background-color:transparent;border:0.5px solid" disabled><i class="fa fa-calendar"></i></button>
                                    </div>
                                    @Html.EditorFor(model => model.TicketPurchaseDate, new { htmlAttributes = new { @class = "datepicker form-control", autocomplete = "off" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.TicketPurchaseDate, "", new { @class = "text-danger" })


                            </div>
                        </div>

                        <div class="col-5">
                            @*Time picker*@

                            <label class="col-form-label">Time</label>
                            <div class="input-group mb-4">
                                <div class="input-group-prepend">
                                    <button id="button-addon7" type="submit" class="btn btn-primary" style="color:black;background-color:transparent;border:0.5px solid" disabled><i class="fa fa-clock-o"></i></button>

                                </div>
                                <input id="time" type="search" placeholder="Time" aria-describedby="" class="form-control">
                            </div>
                        </div>
                    </div>

                    <div class="row justify-content-start">
                        <div class="col-3">
                            <label class="col-form-label" style="margin-left: 35px">Passengers</label>
                        </div>
                    </div>


                    @*Adult selector*@

                    <div class="container-fluid">

                        <div class="form-row">

                            <div class="input-group align-items-center">

                                <span class="input-group-btn"><button type="button" class="btn-circle btn-circle-sm m-1 btn-info value-control font-weight-bolder border-0" data-action="minus" data-min="0" data-target="adult-select"><span class=""></span>-</button></span>
                                <input type="text" maxlength="1" minlength="1" value="0" class="form-control text-center" id="adult-select" style="max-width: 50px; max-height: 50px;" onkeypress="return isNumber(event)" />
                                <span class="input-group-btn"><button type="button" class="btn-circle btn-circle-sm m-1 btn-info value-control font-weight-bolder border-0" data-action="plus" data-max="9" data-target="adult-select"><span class=""></span>+</button></span>
                                <text>Adult</text>

                            </div>

                            @*Student selector*@

                            <div class="input-group align-items-center">


                                <span class="input-group-btn"><button type="button" class="btn-circle btn-circle-sm m-1 btn-info value-control font-weight-bolder border-0" data-action="minus" data-min="0" data-target="student-select"><span class=""></span>-</button></span>
                                <input type="text" maxlength="1" value="0" class="form-control text-center" id="student-select" style="max-width: 50px; max-height: 50px;" onkeypress="return isNumber(event)" />
                                <span class="input-group-btn"><button type="button" class="btn-circle btn-circle-sm m-1 btn-info value-control font-weight-bolder border-0" data-action="plus" data-max="9" data-target="student-select"><span class=""></span>+</button></span>
                                <text>Student</text>

                            </div>

                            @*Child selector*@

                            <div class="input-group align-items-center">


                                <span class="input-group-btn"><button type="button" class="btn-circle btn-circle-sm m-1 btn-info value-control font-weight-bolder border-0" data-action="minus" data-min="0" data-target="child-select"><span class=""></span>-</button></span>
                                <input type="text" maxlength="1" value="0" class="form-control text-center" id="child-select" style="max-width: 50px; max-height: 50px;" onkeypress="return isNumber(event)" />
                                <span class="input-group-btn"><button type="button" class="btn-circle btn-circle-sm m-1 btn-info value-control font-weight-bolder border-0" data-action="plus" data-max="9" data-target="child-select"><span class=""></span>+</button></span>
                                <text>Child</text>

                            </div>

                            <div id="passenger-error">

                            </div>


                            <div class="input-group justify-content-end">

                                <button id="find-ticket" class=" btn btn-lg btn-info text-white m-3" onclick="return false"> Find tickets </button>
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </div>

    </div>

}

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.4.1.slim.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>


<script>

    // Add the supported stations and times to autocomplete textboxes
    $(function () {
        var availableStation = [
            "Oslo s",
            "Nationaltheatret",
            "Lysaker",
            "Bergen",
            "Myrdal"
        ];

        var availableTime = [
            "11:00",
            "12:00",
            "13:00",
            "14:00",
            "15:00"
        ];
        $("#station1, #station2").autocomplete({
            source: availableStation,
            minLength: 0
        });

        $("#time").autocomplete({
            source: availableTime,
            minLength: 0
        });

    });

    $("#time").click(function () {

        $("#time").autocomplete("search", "");

    });

    $("#station1").click(function () {

        $("#station1").autocomplete("search", "");

    });

    $("#station2").click(function () {

        $("#station2").autocomplete("search", "");

    });

    // Add logic to plus & minus buttons
    $(document).on('click', '.value-control', function () {

        var action = $(this).attr('data-action')
        var min = $(this).attr('data-min')
        var max = $(this).attr('data-max')
        var target = $(this).attr('data-target')
        var value = parseFloat($('[id="' + target + '"]').val());

        if (isNaN(parseFloat($('[id="' + target + '"]').val()))) {

            return (parseFloat($('[id="' + target + '"]').val(0)));

        } else {

            if (action == "plus") {

                if (value < max) {
                    value++;
                }
            }
            if (action == "minus") {
                if (value > min) {
                    value--;
                }
            }
            $('[id="' + target + '"]').val(value)
        }
    });


    // Prevent letters in numeric input fields
    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }
</script>
@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        // Setup the datepicker
        $(function () {
            $(".datepicker").datepicker({
                showOn: "focus",
                dateFormat: "mm.dd.yy",
                changeMonth: true,
                changeYear: true,
                minDate: new Date(),
                maxDate: "+3m",

            });
        });

        $(document).ready(function () {

         // validate the form and submit if all fields are vaild. 
            $("#find-ticket").click(function () {
                var isValid = $("#find-ticket-form").valid();
                    if (isValid) {
                    find_ticket();
                    }      
                  });

                // Find the availabe tickets
                function find_ticket() {
                    var TicketPurchaseDate = $(".datepicker").datepicker("getDate");
                    var StartStation = $("#station1").val().toString().substring(0, 10);
                    var EndStation = $("#station2").val();
                    var adultCount = $("#adult-select").val();
                    var studentCount = $("#student-select").val();
                    var childCount = $("#child-select").val();
                    var ticketDuration = 0;
                    var passengers = [];

                    if (adultCount == 0 && studentCount == 0 && childCount == 0) {
                        $("#passenger-error").append("<p class='text-danger mt-3'> You have to choose at least one passenger!</p>");
                    }
                    else {

                    if (adultCount > 0) {
                        for (var i = 0; i < adultCount; i++) {
                            passengers.push({ "PassengerType": "Adult" });

                        }
                    }

                    if (studentCount > 0) {
                        for (var i = 0; i < studentCount; i++) {
                            passengers.push({ "PassengerType": "Student" });

                        }
                    }

                    if (childCount > 0) {
                        for (var i = 0; i < childCount; i++) {
                            passengers.push({ "PassengerType": "Child" });

                        }
                    }


                    var ticket = {
                        "TicketPurchaseDate": TicketPurchaseDate,
                        "StartStation": StartStation,
                        "EndStation": EndStation,
                        "TicketDuration": ticketDuration,
                        "TicketPassengers": passengers


                    }
                    // Post the ticket to the Route page
                    $.ajax({
                        url: '@Url.Action("Index","Route")',
                        contentType: 'application/json',
                        type: 'POST',
                        data: JSON.stringify(ticket),
                        success: function (data) {
                            $(location).attr('href', "/Route");
                        }

                    });

                    }
                        }
                });
    </script>
}

Vy/Views/Home/Liste.cshtml
@model List<Vy.Models.Passenger>

<body>
    <div>
        <table class="table">
            <tr>
                <th>Email</th>
                <th>Ticket Price</th>
                <th>Ticket Number</th>
                <th>Travellings Class</th>
                <th>Date Of Journey</th>
                <th>Time Of Journey</th>
                <th>Transports Number</th>
                <th>Source</th>
                <th>Destination</th>
                <th>Arrival Time</th>
                <th>Departure Time</th>
            </tr>
            @foreach (var passenger in Model)
            {
        <tr>
            <td>@passenger.email</td>
            <td>@passenger.ticketPrice</td>
            <td>@passenger.ticketNumber</td>
            <td>@passenger.travellingClass</td>
            <td>@passenger.dateOfJourney</td>
            <td>@passenger.timeOfJourney</td>
            <td>@passenger.transportNumber</td>
            <td>@passenger.source</td>
            <td>@passenger.destination</td>
            <td>@passenger.arrivalTime</td>
            <td>@passenger.departureTime</td>
            <td><a href="/Home/delete?=@passenger.email" class="btn btn-danger">Delete</a></td>

        </tr>
            }

        </table>
        <a href="/Home/Book" class="btn btn-info">Book a new one</a>
    </div>
</body>